parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    impliedStrict: true
env:
  browser: true
  es6: true
  jest: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
globals:
  echarts: true
rules:
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    -
      allowTemplateLiterals: true
  semi:
    - error
    - always
  comma-dangle:
    - error
    - objects: never
  arrow-parens:
    - error
    - always
